### ISSUE TITLE
Requirements.txt installation fail because of how the version is specified

### ISSUE THREAD

**Issue by baristahell** [sdrdis/nn#1]
Hello @sdrdis, thanks for this package !
Small issue with the installation thought, **pip** and **conda** fail to find `keras-2.2.2` and `tensorflow-1.10.0` (ubuntu 16.04)

A suggestion to fix this would be to change the affected lines to :
`keras==2.2.2`
`tensorflow==1.10.0`

**Comment by sdrdis** [comment]
Fixed! Thanks for reporting the issue!
